# netlify.toml
[build]
  command = "mkdocs build"
  publish = "site/"
  environment = { PYTHON_VERSION = "3.13.7"}

[[redirects]]
    from = "https://www.circuitpythonshow.com/@thebootloader/feed.xml"
    to = "https://feeds.captivate.fm/thebootloader/"
    status = 301
    force = true
